# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 01:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lines',
            new_name='Line',
        ),
    ]
