# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_auto_20161215_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='text_arr',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='line',
            name='text_dep',
            field=models.CharField(default='', max_length=100),
        ),
    ]
