# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_auto_20161215_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='city_arr',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='line',
            name='city_dep',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='line',
            name='rinko_arr',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='line',
            name='rinko_dep',
            field=models.CharField(max_length=10),
        ),
    ]
